# ---------------------
# PiHomeAlone settings
# Use YAML syntax
# ---------------------
# debug mode
debug: True

# This is the valid pin code to type to enable or disable the alarm from the keyboard
pin_code: 1234

# Valid UID captured by the RFID reader
rfid:
  valid_uid:
    - [52, 100, 147, 133, 70]
    - [197, 86, 167, 117, 65]

# Valid UID captured by the 433MHZ receiver
sensors:
  - id: 6481558
    location: Kitchen
  - id: 9532938
    location: Living room
  - id: 15732234
    location: Bedroom


# ---------------------------
# Availlable backends:
#
# Pushetta: http://www.pushetta.com/
#
backends:
    - pushetta

pushetta:
