# ---------------------
# PiHomeAlone settings
# Use YAML syntax
# ---------------------
# debug mode
debug: True

# This is the valid pin code to type to enable or disable the alarm from the keyboard
pin_code: 1234

# Valid UID captured by the RFID reader
rfid:
  valid_uid:
    - [52, 100, 147, 133, 70]
    - [197, 86, 167, 117, 65]

# Valid UID captured by the 433MHZ receiver
sensors:
  - id: 6481558
    location: Kitchen
  - id: 9532938
    location: Living room
  - id: 15732234
    location: Bedroom


# This is the time an user will have to disable he system after an intrusion detection.
# Not that this settings must be apllied on the Arduino code side. You must set the variable "long delay_time" into the arduino code
# to the same value as configured here. Aduino talk in milliseconds, RPI in secondes so 20s = 20000ms
# E.g:
# RPI settings: wait_time_before_alarm: 20
# Arduino code: long delay_time = 20000;
wait_time_before_alarm: 20

# time to enable
arming_time: 20

# Switch this to true if you want to just receive a notification after the system has switched to alarming status
notification_only: true

# ---------------------------
# The notification backend is used to notify the user when the system switch into alarming status.
# A message that contain the location of the intrusion
#
# Availlable backends:
#
# Pushetta: http://www.pushetta.com/
#
backends:
    - pushetta

pushetta:
  api_key: a014ed642fc5be3db4fa894ce2a16e8e6e8e38b3
  channel_name: PiHomeAlone